<?php
session_start();

$loggedInUser = $_SESSION['username'] ?? ''; // Get the logged-in username from the session

//this codes gather the level and other information of the students and save it in the database and also save the photo in the session to be used in the card.php file to generate the ID card with the photo of the student
$conn = new mysqli("sql304.ezyro.com", "ezyro_41858239", "ed50a9d455d79a7", "ezyro_41858239_id");
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$sql = "SELECT name, matricule, level, photo_path, created_at FROM students_info WHERE username = '$loggedInUser' ORDER BY created_at DESC";//logs the history of the ID cards generated by the user and display it in the history.php file with the photo of the student and the date of generation of the ID card
$result = $conn->query($sql);

function formatHistoryDate($date)
{
    $timestamp = strtotime($date);
    return $timestamp ? date('M j, Y · g:i A', $timestamp) : $date;
}

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
</head>

<body>
    <style>
        .heading {
            display: flex;
            flex-direction: column;
            align-items: center;
            margin-top: -10px;
            text-align: center;
        }

        .heading h1 {
            margin: 0;
            font-size: 2rem;
            color: #0f172a;
        }

        .icon-box {
            width: 64px;
            height: 64px;
            border-radius: 18px;
            background: #dbeafe;
            color: #1d4ed8;
            display: grid;
            place-items: center;
            font-size: 1.5rem;
            margin-bottom: 15px;
        }

        body {
            margin: 0;
            padding: 0;
            min-height: 100vh;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background:
                radial-gradient(circle at top right, rgba(191, 219, 254, 0.55), transparent 30%),
                linear-gradient(135deg, #eef5ff 0%, #f8fbff 48%, #eaf3ff 100%);
        }

        /* 2. THE MENU BAR (FULL WIDTH) */
        .menu-bar {
            background-color: #ffffff;
            width: 100%;
            /* Stretches to both edges */
            height: 50px;
            display: flex;
            align-items: center;
            padding: 0 40px;
            /* Padding for the text inside */
            box-sizing: border-box;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);
            font-weight: 700;
            color: #1e293b;
            font-size: 1.2rem;
            position: sticky;
            /* Stays at the top when scrolling */
            top: 0;
            z-index: 1000;
        }

        .menu-bar :hover {
            color: #9bbcff;

        }

        .content-container {
            width: 100%;
            max-width: 780px;
            /* Limits the form width for readability */
            margin: 40px auto;
            /* Centers the form on the page */
            padding: 0 20px;
            box-sizing: border-box;
            transition: filter 0.2s ease, opacity 0.2s ease;
        }

        body.menu-open .content-container {
            filter: blur(2px);
            opacity: 0.7;
            pointer-events: none;
        }

        /* This is one saved ID history row. */
        .history-card {
            display: flex;
            align-items: center;
            gap: 18px;
            min-height: 90px;
            height: auto;
            padding: 18px 22px;
            margin-top: 28px;
            border-radius: 20px;
            background: rgba(255, 255, 255, 0.9);
            border: 1px solid rgba(226, 232, 240, 0.85);
            box-shadow: 0 14px 35px rgba(30, 64, 175, 0.12);
        }

        /* Empty image area. Later, you can replace this with the real student photo. */
        .student-photo {
            width: 96px;
            height: 96px;
            border-radius: 16px;
            background: #e2e8f0;
            border: 2px solid #93c5fd;
            display: grid;
            place-items: center;
            color: #64748b;
            font-size: 0.9rem;
            flex-shrink: 0;
            text-align: center;
            overflow: hidden;
        }

        .student-photo img {
            width: 100%;
            height: 100%;
            object-fit: cover;
            display: block;
        }

        /* This area holds the name, matricule, level, and date. */
        .student-details {
            flex: 1;
            min-width: 0;
        }

        .student-name {
            margin: 0 0 8px;
            font-size: 1.25rem;
            font-weight: 600;
            color: #0f172a;
        }

        .student-matricule,
        .student-level,
        .history-date {
            margin: 0;
            font-size: 1.05rem;
            color: #475569;
        }

        .history-date {
            margin-top: 8px;
        }

        .student-matricule strong {
            color: #1e293b;
        }

        /* These are the action buttons on the right side of the card. */
        .download-history,
        .delete-history {
            width: 48px;
            height: 48px;
            border: none;
            border-radius: 14px;
            font-size: 1.35rem;
            cursor: pointer;
            flex-shrink: 0;
        }

        .download-history {
            background: #eff6ff;
            color: #1d4ed8;
        }

        .download-history:hover {
            background: #dbeafe;
        }

        .delete-history {
            background: #fef2f2;
            color: #dc2626;
        }

        .delete-history:hover {
            background: #fee2e2;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            z-index: 1001;
            background-color: white;
            padding: 10px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);

        }

        .dropdown-content .logout {
            color: #ef4444;
        }

        .dropdown-content .logout:hover {
            background-color: #b91c1c30;
            border-radius: 10px;

        }

        .dropdown-content {
            height: calc(100vh - 50px);
            width: 200px;
        }

        .dropdown-content li {
            color: #1d4ed8;
        }

        .dropdown-content li:hover {
            background-color: #e2e8f0;
            border-radius: 10px;
        }

        .dropdown-content li .active {
            background-color: #93c5fd;
            color: white;
            border-radius: 10px;
        }

        @media (max-width: 500px) {
            .menu-bar {
                padding: 0 20px;
            }

            .content-container {
                width: calc(100% - 28px);
                max-width: 460px;
                margin: 28px auto;
                padding: 0;
            }

            .heading h1 {
                font-size: 1.75rem;
            }

            .history-card {
                gap: 12px;
                min-height: 0;
                padding: 12px;
                margin-top: 18px;
                border-radius: 16px;
                box-shadow: 0 10px 26px rgba(30, 64, 175, 0.1);
            }

            .student-photo {
                width: 72px;
                height: 72px;
                border: 0;
                border-radius: 12px;
            }

            .student-name {
                font-size: 1.15rem;
                line-height: 1.1;
                margin-bottom: 5px;
            }

            .student-matricule,
            .student-level,
            .history-date {
                font-size: 0.9rem;
                line-height: 1.25;
            }

            .student-level,
            .history-date {
                display: inline-block;
                margin-top: 5px;
            }

            .history-date {
                margin-left: 18px;
            }

            .download-history,
            .delete-history {
                width: 36px;
                height: 36px;
                border-radius: 12px;
                font-size: 1.05rem;
            }

            .download-history {
                background: #eff6ff;
                color: #1d4ed8;
                margin-left: auto;
            }

            .delete-history {
                display: inline-flex;
                align-items: center;
                justify-content: center;
            }
        }
    </style>

    <div class="menu-bar" onclick="toggleDropdown()">
        <div class="dashboard-icon" style="gap: 3px;"><i class="fa-solid fa-bars"></i></div>
        Dashboard
    </div>

    <div class="dropdown-content" id="dropdown-content"
        style="display: none; position: absolute; z-index: 1001; background-color: white; padding: 10px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);">
        <ul style="list-style: none; margin: 0; padding: 0;">
            <li class="id" style="padding: 8px 12px; cursor: pointer;"
                onclick="window.location.href = 'dashboard.html'">
                <i class="fa-solid fa-id-card"></i> Create ID
            </li>
            <li class="profile" style="padding: 8px 12px; cursor: pointer;" onclick="window.location.href = 'card.php'">
                <i class="fa-solid fa-download"></i> Download ID
            </li>
            <li class="history" style="padding: 8px 12px; cursor: pointer;"
                onclick="window.location.href = 'history.php'"><i class="fa-solid fa-clock"></i>History
            </li>
            <li class="logout" style="padding: 8px 12px; cursor: pointer;"
                onclick="window.location.href = 'logout.php'"><i class="fa-solid fa-sign-out-alt"></i>Logout</li>


        </ul>
    </div>
    <div class="content-container">
        <div class="heading">
            <div class="icon-box"><i class="fa-solid fa-id-card"></i></div>
            <h1>Student ID Generator</h1>
        </div>

        <!-- One example history item -->
         <?php while ($row = $result->fetch_assoc()): ?>
        <div class="history-card">
            <!-- Empty place for student picture -->
             
            <div class="student-photo">
            <?php if (!empty($row['photo_path'])): ?>
                <img src="data:image/jpeg;base64,<?php echo base64_encode(($row['photo_path'])); ?>" alt="Student photo">    
            <?php else: ?>
                No photo
            <?php endif; ?>
            </div>

            <!-- Student ID details -->
            <div class="student-details">
                <h2 class="student-name"><?php echo htmlspecialchars($row['name']); ?></h2>
                <p class="student-matricule">Mat <strong><?php echo htmlspecialchars($row['matricule']); ?></strong></p>
                <p class="student-level"><?php echo htmlspecialchars($row['level']); ?> Level</p>
                <p class="history-date"><?php echo htmlspecialchars(formatHistoryDate($row['created_at'])); ?></p>
            </div>

            <!-- Download button -->
            <button class="download-history" title="Download ID">
                <i class="fa-solid fa-download"></i>
            </button>

            <!-- Delete button -->
            <button class="delete-history" title="Delete history">
                <i class="fa-solid fa-trash"></i>
            </button>
        </div>
        <?php endwhile; ?>

    </div>

    <script>
        function toggleDropdown() {
            var dropdown = document.getElementById("dropdown-content");
            if (dropdown.style.display === "block") {
                dropdown.style.display = "none";
                document.body.classList.remove("menu-open");
            } else {
                dropdown.style.display = "block";
                document.body.classList.add("menu-open");
            }

        }
    </script>
</body>

</html>
